# Generated by Django 5.1.1 on 2025-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_phone_numbre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
