# Generated by Django 5.1.1 on 2025-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0002_order_guest_phone_numbre_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='No city provided', max_length=25),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='No city provided', max_length=25),
        ),
    ]
